apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
spec:
  project: default
  source:
    repoURL: github.com/argoproj/argo-helm
    path: charts/argocd-notifications
    targetRevision: argocd-notifications-1.8.1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
