apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- resources/namespace.yaml
- argocd-applicationset-controller-metrics.yaml
- argocd-dex-server.yaml
- argocd-metrics.yaml
- argocd-notifications-controller.yaml
- argocd-redis-haproxy-metrics.yaml
- argocd-repo-server-metrics.yaml
- argocd-server-metrics.yaml
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.1.1
patches:
- path: patches/argocd-cm.yaml
- path: patches/argocd-server-deployment.yaml
- path: patches/argocd-repo-server-deployment.yaml
- path: patches/argocd-application-controller-statefulset.yaml
